### ISSUE TITLE
Attendance days to hr.payslip

### ISSUE THREAD

**Issue by hitrosol** [OCA/payroll#110]
I'm glad to see this repo is actively maintained by OCA. It's kind of loss since V13 it was moved to EE.
This repo is become more complete and hopefully  there will new other features coming soon.

One of my feature I think I can't find right now is to get the attendance days to be imported to worked_days. As default it shows the WORKS.100 but, it's good to calculate the total days from the attendance to payslip. Having overview about the attendance and the time off will help user to get rid the conflict between the scheduled. 

The second, it would be good as well if we can compensate the receivable / payable that was created from Expense Module to be factored in payslip. Currently, we can use Inputs and fill the amount manually, but if we can import it automatically from the approved expense, that will be great. One of the use case I found is about deduct the payroll by the staff loan instalment.

Thanks for considering items for the next round.

**Comment by nimarosa** [comment]
Hello, yes the changes you suggest are in roadmap for me. 

Both must be separate modules that link hr_attendance and hr_expense to payroll. The implementation is quite easy because you now have a lot of hook methods to push information to worked days and inputs. 

For now, I don't have time to work on this so if you or anyone wants to make que PR with this new modules it will be great. 

Also if we implement hr_attendance in payroll we will have to make a setting to use hr_leaves with attendance. 

But yea, this modules should be included in this repo, that way we have a complete payroll solution.
