### ISSUE TITLE
Global rule blacklist ban rule for next contacts

### ISSUE THREAD

**Issue by voronind** [OCA/payroll#127]
Global rule blacklist ban rule for next contacts

## Module
payroll

## Describe the bug
Rules can not appear in Paysplips depends on contract computing order.

## To Reproduce
**Affected versions**: 13-16

1. Create 2 open contracts for same employee with same structure and wages 1 and 10
2. Add "C" rule to this structure with code condition: result = contract.wage > 5
3. Create Payslip for our employee without specified Contract to compute 2 added contracts in this payslip
4. Compute payslip.

**Expected behavior**
Payslip lines will have C rule in any cases.
But if Odoo will compute contract with wage = 1 firstly, Payslip will not contain C rule at all.
This happens cause if condition is negative Odoo adds rule to global blacklist and second contract ignores C rule at all.

IMHO We must create blacklist for every contract.

**Comment by nimarosa** [comment]
Hello @vernichon, actually i think this behavoir is because we don't reset the blacklist in every contract iteration in the function get_lines_dict(), so, as you described, rule will be in the blacklist for the next contract if it's the same rule. 

I can write a fix for this in a few days, or if you want you can open a PR. The only change needed is to include blacklist reset inside the contract loop in that function.
