### ISSUE TITLE
contribution.register documentation

### ISSUE THREAD

**Issue by ghost** [OCA/payroll#48]
Hi friends,

What is the purpose of the contribution.register?

**Comment by mtelahun** [comment]
Hi Henrik,

I don't know what the intention of the original developers was but I 
find it useful for cross-checking payroll to some other company defined 
policies. For example, I have an hr_benefit module that I use to handle 
things like employee advantages and premiums. So two of those things may 
be Labour Union dues (deducted from the employee and paid to the labour 
union) and Provident Fund (with an employee deducted part and an 
employer contribution part). Each of the salary rules related to this 
are assigned a contribution register. I have other modules  that check 
correctness of payroll and one of those checks is that labour union dues 
are deducted from every employee who is a member of a the labour union. 
Another check is that the the employer contributed part is correctly 
applied to the payslip of every employee that has a provident fund 
benefit. Instead of checking each payslip individually I can just use 
the contribution registers for this. Also, I don't have to do this check 
in-line with payroll generation. I can run it as a separate job when the 
system isn't in use.

If it's just a few employees it doesn't matter but when you're handling 
payroll for several thousand employees time-savers like this matter.

Regards,

Mike

**Comment by nimarosa** [comment]
@appstogrow As it is now, the contribution_register is used only for reporting. You have one report that groups the sum of the rules that are associated to that contribution_register. The idea is to use contribution_register to have a register of all the rules that inject or deduct money from the payslip on behalf on third orgamism (could be the government, the labour union, etc).

As it happen with hr_contract_advantage_templates it is a not finished functionality in my opinion. 

I'm planning extending that approach to show in the views the summary of contribution register for each payslip, because it can be useful to know how much money you need to deposit/pay to external organism.

**Comment by ghost** [comment]
I see that the payslip action menu Payslip Lines will show only lines associated with a contribution register.

**Comment by nimarosa** [comment]
@appstogrow Are you sure? Not on my end, see all related lines in that action. Will test in clean install to see.

**Comment by TheCloneMaster** [comment]
Contribution registers are used to associate the resulting payslip line to a partner.
This is useful for example to register account payables/receivables.
