### ISSUE TITLE
Merge of hr_payroll_cancel and hr_payroll_change_state. 

### ISSUE THREAD

**Issue by nimarosa** [OCA/payroll#54]
Modules hr_payroll_cancel and hr_payroll_change_state. 

Should we merge this modules logic into payroll module itself? Or maybe just provide this functionality in the base payroll module so we don't need that modules? 

I don't think the point of maintaining more two modules whose purpose  is to add the functionality of mass change states and cancelation. We can just plug-in this functionality to the base module. 

What do you think?

**Comment by mtelahun** [comment]
While the functionality in these modules is useful it's not essential 
for the payroll module to function correctly. I think we should keep the 
base payroll module as basic as possible and allow people to pick and 
choose what other functionality they want by installing other modules on 
top of it.

**Comment by pedrobaeza** [comment]
I consider the cancel option a base feature.

**Comment by mtelahun** [comment]
I disagree, but I won't oppose the merge.

**Comment by pedrobaeza** [comment]
MIchael, take into account that anyone may make any mistake. and not being able to amend it is not good IMO.

**Comment by mtelahun** [comment]
Hi Pedro,

Like I said I won't oppose the change. I also understand that anyone can 
make a mistake and in that scenario the ability to cancel the payslip 
and start again is useful. But just for arguments sake consider the 
following scenario. Let's say you're a company that has tens of 
thousands of employees and you have an automated payroll system. In this 
scenario you don't want to give your payroll staff the ability to modify 
individual payslips. For one thing, it's inefficient and second, with 
that many employees it becomes harder to detect fraud. If a payroll 
staff notices a problem you want them to change the **source** of the 
problem and then re-generate the payslip through the system.

I understand that a lot of Odoo users are of the small and medium 
enterprise type that do not have the problems I'm talking about and 
would prefer to have the ability to cancel a payslip built-in rather 
than install an additional module. Also, if you have tens of thousands 
of employees you should also have the ability to install or build a 
module that takes that functionality away. So it could be argued that a 
majority of users prefer to have the functionality, which is why I won't 
oppose the change.

I don't take opposing views just to be confrontational I usually have a 
reason. I hope you don't mind :-P

**Comment by pedrobaeza** [comment]
Thanks for bringing such concerns. I think we can just protect that feature under a configuration option "Enable payslip cancelling"  or similar, so that only system administrators can modify this and if disabled, payroll managers won't be able to do it although the feature is integrated. What do you think?

**Comment by nimarosa** [comment]
Hello, I agree with @pedrobaeza that we could protect the feature. Maybe a setting it's not necessary: we can work in improving the user security groups and make more roles with restrictive permissions, or add this feature security group in a checkbox in user settings (security) like some other modules do, it could be "Allow to cancel payslips" checkbox. 

Also @mtelahun pointed to a case when you automated payroll and want the users to only work in the system. But we can make the cancellation process something an administrator can approve. Also with current security groups the user with the fewer payroll rights can edit anything in the payslip, which is not recommended for an automated payroll, that's other reason to work in improving security groups. 

Also I want to vote for also merge the change_state wizard to the base module. As I see it, it's a basic function the user would expect: if the business has like 100 payslips per payroll process, the user will expect to select all and approve all of them. With the current behavior the user will have to enter each payslip to approve it and the follow to the next one. In a large payroll this will be expected. Also if you guys don't want to merge change_state to the base module we can work in at least having buttons in tree view to deal with the approval. 

What you think?

**Comment by pedrobaeza** [comment]
I prefer a setting to unlock the feature, as other group or other validation mechanisms will make this more convoluted with no reason. With this setting, Michael's concern - which were legitimate - are attended, so let's not invent more use cases until they are needed by our real users.

**Comment by nimarosa** [comment]
@pedrobaeza Great so a setting will be. I can start working on it and propose a PR with the feature. 

What about the change_state module? 

@appstogrow any opinion about this?

**Comment by dantrix** [comment]
Hello, 
+1 for Settings instead user or groups.

+1 for include Change status in module.

**Comment by ghost** [comment]
> Hello, 
> +1 for Settings instead user or groups.
> 
> +1 for include Change status in module.

I agree

**Comment by ghost** [comment]
@mtelahun If "hr_payroll_change_state" is merged into "payroll", will you then have to remove the feature for your client? If so, would you like "payroll" to have another option in settings to turn on/off the feature?

**Comment by nimarosa** [comment]
Closed since #63 and #64 integrates this changes.

**Comment by mtelahun** [comment]
I think that's a great suggestion.
