### ISSUE TITLE
Which payroll features are essential?

### ISSUE THREAD

**Issue by norlinhenrik** [OCA/payroll#92]
In general, I think that `payroll` should have essential features only. I am not using:

* Contribution register
* Worked days
* Other inputs
* "Salary rules appearing on payslip" (details_by_salary_rule_category)
* Codes (I don't always need them, why are they required in salary rule, category & structure?)
* Child rules
* Python in salary rules (I use it now, but I would like to make a flexible alternative)

@nimarosa @mtelahun @pedrobaeza @percevaq 
Are you using all of these features?
Is there any other `payroll` feature that you are not using?
Do you think that anything should move to another module, or be enabled with a setting?
**Please write short answers!**

**Comment by nimarosa** [comment]
Hello, actually I'm using all of them. Also I think that as a base module it should have at least the main functions that a profesional payroll system has. So I think the functions listed are a essential part of the system, should not be moved to other modules or disables with settings.  

- worked_days: for me is essential. How do you deduct leaves without it?
- inputs: very useful for retrieving external data that you need. Also useful to add manual data to payslip. 
- details_by_salary_rule_category: useful for retrieving only the rules that appears on payslip and only parent rules. I use it in reporting mainly. 
- codes: codes are required to retrieve computed salary rules and categories amounts from inside rules. How do you do it without them? 
- child rules: i mainly use them
to make auxiliary calculations that are used by other rules. Also useful for adding rules to the computation only if the parent is there. 

Finally I use contribution register for reporting but I always thought that it can be replaced by a partner_id relation in the rules, it will achieve the same functionality. Maybe I introduce this change in the future.

**Comment by mtelahun** [comment]
While I don't think the current module can be reduced by much, I am not 
against moving features behind settings or into other modules if someone 
else is willing to do the work. Also, I think the word essential is 
loaded. Some features I think are essential may not be so for others. I 
prefer the words basic and optional.

Basic - a feature fundamental to the payroll process or necessary for 
other payroll features to work

Optional - stand-alone feature that an implementer can choose to use or not


- Contribution register

Optional. But essential for me. Used for reporting and cross-checking. 
There might be a better way of doing it, but I don't have time/resources 
to look for one.

- Worked days

Optional. While many organizations do use this feature many small 
organizations with salaried workers aren't interested in tracking their 
employees work hours. They leave it to the employees and their managers 
to work out scheduling issues, leaves, etc. From a payroll processing 
standpoint not calculating work days can probably save some time in 
payroll calculations. Can probably be moved behind a setting.

- Other inputs

Optional. Every organization I have worked with has needed some way to 
make one-off additions or subtractions to a payslip so it would appear 
to be a basic feature. However, it can probably be moved behind a setting.

- details by salary rule category

Optional - in the many years I've worked with OpenERP (and then Odoo) I 
have never had any occasion to use it. Not even once.

- Codes

Basic - Without them you can't write salary rules that reference other 
rules.

- Child rules

Basic - This is a close one because it's not a feature used a lot, but 
it is essential for writing progressive income tax rules.

- Python in salary rules

Basic - every payroll system needs some way to make calculations with 
rules. For example, NET = GROSS - DEDUCTIONS. Short of writing our own 
domain specific payroll calculation language this will remain essential.


Regards,

Mike.
